Feature/oam
hgranule/GameBoyEMU pull request #1
Opened 2021-05-17 13:12 UTC by dolovnyak

2021-05-17 18:52 UTC, hgranule commented
vaddr
virt_addr
inner_vaddr
phys_addr
paddr

2021-05-17 19:24 UTC, hgranule requested changes
read_inner_vaddr();
read_vaddr();
write_paddr();

virtual address/ physical address / inner virtual address
read_NAME_reg
get_NAME_reg

2021-05-17 19:24 UTC, hgranule commented on include/device/GB_oram.h
> +        inline unsigned __calc_phys_addr(word_t raw_logic_addr) const;
useless

2021-05-17 19:24 UTC, hgranule commented on test/wram.cc
> +#include <gtest/gtest.h>
Stop changing my code. Gtest isn't our system library, we download it from WWW, just in our workspace. use "

2021-05-17 19:24 UTC, hgranule commented on test/oram.cc
> +#include <gtest/gtest.h>
the same

2021-05-17 19:24 UTC, hgranule commented on sources/wram.cc
> +                    , memory::BusInterface::ReadCmd(read_logic_addr_gb_wram)
REVERT ALL CHANGES THAT YOU MADE TO MINE CODE. Use TODO in future

2021-05-17 19:24 UTC, hgranule commented on test/oram.cc
> +        EXPECT_EQ(oram.get_raw_memory().size(), 160);
len

2021-05-17 19:24 UTC, hgranule commented on test/oram.cc
> +        EXPECT_EQ(oram.get_raw_memory().size(), 160);
add size() / length()

2021-05-17 19:24 UTC, hgranule commented on sources/oram.cc
> +    {
Check all your code with cpplint.py

2021-05-17 19:24 UTC, hgranule commented on include/device/GB_oram.h
> +#define GB_ORAM_H
cpplinter

2021-05-17 19:24 UTC, hgranule commented on include/device/GB_oram.h
> +#include <vector>
WTF?

2021-05-17 19:24 UTC, hgranule commented on include/device/GB_oram.h
> +    public:
linter

2021-05-17 19:24 UTC, hgranule commented on include/device/GB_wram.h
> +    inline u32 __calc_phys_addr(word_t raw_logic_addr) const {
don't touch it, but leave me a TODO(hgranule): move outside

2021-05-17 19:24 UTC, hgranule commented on include/device/GB_wram.h
> +        const u32 bankIdx = (raw_logic_addr >= memory::WRAMX_BASE_VADDR)
leave me a todo abou camel case

2021-05-17 19:24 UTC, hgranule commented on include/memory/GB_vaddr.h
> +    OAM_ECHO_BASE_VADDR = 0xFEA0,
revert

2021-05-17 19:24 UTC, hgranule commented on test/oram.cc
> +// TODO: make unit-tests for read/write with memory_bus when it will be done
(dolovnyak)

2021-05-18 13:06 UTC, dolovnyak commented on .gitignore
> +*cmake-build-debug/
most likely thing with gitignore which we talked about, because of you push force after my first commit, when I changed gitignore

2021-05-18 13:25 UTC, hgranule requested changes

2021-05-18 13:25 UTC, hgranule commented on include/device/GB_oram.h
> +    inline byte_t read_inner_vaddr(word_t inner_vaddr) const;
OAM has no inner virtual adress space, as I told you yesterday. Rename it to simple `read` or to `read_phys_addr`.

2021-05-18 13:25 UTC, hgranule commented on include/device/GB_oram.h
> +    ~ORAM();
Delete all Copy/Move constructors. As I know, they already self-implemented by CC, and their implementation is the same. If I'm not right, show me it pls.

2021-05-18 13:25 UTC, hgranule commented on include/device/GB_oram.h
> +ORAM::get_raw_memory() const {
1) Rename it to `get_memory_buffer`.

2) Are you sure that you need to copy that buffer, it's stupid. Maybe you need to return a const reference????

2021-05-18 13:25 UTC, hgranule commented on include/device/GB_oram.h
> +ORAM::get_raw_memory() const {
If it must rrturn reference, use the next name: `get_memory_buffer_ref`

2021-05-18 13:28 UTC, hgranule commented on .gitignore
> +*cmake-build-debug/
Why?

2021-05-18 15:01 UTC, dolovnyak commented on include/device/GB_oram.h
> +    ~ORAM();
Then, maybe use = default?

2021-05-18 16:24 UTC, hgranule approved these changes

2021-05-19 12:23 UTC, merged