Feature/vram
hgranule/GameBoyEMU pull request #2
Opened 2021-05-19 18:10 UTC by dolovnyak

2021-05-19 18:54 UTC, hgranule requested changes

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> +        constexpr static u32 RESERVED_BITS = 0xFE;  // TODO(hgranule) I didn't understand how to set range of
```cpp
::bits_set(0, 2, 5, 3, 1);  // 0b00101111
::bit_mask(5, 1); // 0b00111110
```

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> +    struct registers_t {
Registers

standard-like types must be `${type_name}_t`;
All other-types must be -> CamelCased

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> + * @details In DMG mode it always return 0xFE (default VBK_INIT_VALUE), zero bit always set in '0', other always set in '1'.
let it return 0xFE right now, but mark it with
```cpp
// TODO(hgranule): DMG/CGB shit
// <TABS> description
```

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> +VRAM::set_VBK_reg(byte_t value) {
Delete switch/case, you can just NOT map this function (register) to memory!

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> +            __regs.VBK = value | registers_t::RESERVED_BITS;
__regs.VBK = ::bit_n(0, value);

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> +    return __regs.VBK;
return __regs.VBK | RESERVED_BITS;

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> +    if (!(__regs.VBK & 1u))
::bit_n() or just raw value

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> +    if (!(__regs.VBK & 1u))
```cpp
const u32 bank_base = (::bit_n(0, __regs.VBK)) ? VRAM_BANK_SIZE : 0;
return bank_base + bank_offset;
```

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_wram.h
> +    struct Registers {  // TODO(hgranule) codestyle
nope

2021-05-19 18:54 UTC, hgranule commented on include/memory/GB_vaddr.h
> +                                    // TODO(dolovnyak, hgranule): I want to create device GB_echo_oram int the future,
in*

2021-05-19 18:54 UTC, hgranule commented on include/memory/GB_vaddr.h
> +                                    //                            for implementation correct read/write behavior
implementation of shit
implement shit

2021-05-19 18:54 UTC, hgranule commented on test/vram.cc
> +class VRAM_mock : public VRAM {
TODO(dolovnyak):
After last infrastructure change remove MOck and use original class with redefined protected

2021-05-19 18:54 UTC, hgranule commented on test/vram.cc
> +    EXPECT_EQ(vram_mock.get_VBK_reg(), 0xFE);
Split this test to the phys RW and the inner RW

2021-05-19 18:54 UTC, hgranule commented on test/vram.cc
> +    VRAM vram_test_move_constr(std::move(vram));
Please check if dbuffer of vram was moved to that one
Also do it for ORAM

2021-05-19 18:54 UTC, hgranule commented on test/wram.cc
> +#include <utility>  // TODO(hgranule) it not used
Delete it

2021-05-19 18:54 UTC, hgranule commented on test/wram.cc
> +#include <utility>  // TODO(hgranule) it not used
NOT UR COMMNSDA
DELETE MY HEADER DECLARATION

2021-05-19 18:54 UTC, hgranule commented on include/GB_config.h
> +constexpr unsigned VBK_INIT_VALUE = 0xFE;
0x0

2021-05-19 18:54 UTC, hgranule commented on include/GB_config.h
> +    CGB_MODE = 0b001000,
can you add plkease CGB_DMG_MODE = 0b100

2021-05-19 18:54 UTC, hgranule commented on include/common/GB_types.h
> +using Reg8 = byte_t;  // TODO(hgranule) codesyle
Delete it

2021-05-19 18:54 UTC, hgranule commented on include/device/GB_vram.h
> +#include <common/GB_macro.h>
```cpp
#include "OUR HEADERS"
```

2021-05-19 18:54 UTC, hgranule commented on test/wram.cc
>  #include <algorithm>
Delete it too

2021-05-21 00:48 UTC, hgranule approved these changes
Looks good

2021-05-21 01:00 UTC, hgranule commented
For the future:
I think, it's better to commit your "review fixes" commit separately from the previous reviewed commit. That makes review simpler. Let's use `git commit --amend` when there are only 1-3 little fixes, or we can just not use it anymore and use SQUASH and MERGE. What do you think about that???

UPD: Amending and squashing for the master branch. When you work on your Merge Request, better to commit everything separately.

2021-05-21 08:32 UTC, dolovnyak commented
> For the future:
> I think, it's better to commit your "review fixes" commit separately from the previous reviewed commit. That makes review simpler. Let's use `git commit --amend` when there are only 1-3 little fixes, or we can just not use it anymore and use SQUASH and MERGE. What do you think about that???
> 
> UPD: Amending and squashing for the master branch. When you work on your Merge Request, better to commit everything separately.

Ok

2021-05-21 08:33 UTC, merged